---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk6gpv-bus-aprs-prefix
spec:
  replicas: 0
  selector:
    matchLabels:
      name: kk6gpv-bus-aprs-prefix
  template:
    metadata:
      labels:
        name: kk6gpv-bus-aprs-prefix
    spec:
      containers:
        - name: application
          image: areed145/kk6gpv-bus-aprs-prefix:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
